services:
  - type: web
    name: bot-price-analyzer-final
    env: python
    region: frankfurt  # نزدیک به ایران
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false  # Render خودش پر می‌کند
      - key: PORT
        value: 8443
    healthCheckPath: /
    autoDeploy: true
    plan: free
